import { Container, Image } from "react-bootstrap"
import Head from 'next/head'
import { translations } from "@/lib/lang";
import { useContext } from "react";
import LanguageContext from "@/lib/languageContext";

export default function Home() {
  const { language } = useContext(LanguageContext);
  return (
    <>
      <Head>
        <title>Harry Potter Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Container className="text-center">
          <h1 className="top-margin-2 bottom-margin-2">{translations.homePage.title[language]}</h1>
          <Image fluid src="/general.webp" alt="All Characters Poster" width={700} height={500} className="bottom-margin"/>
          <hr className="my-4" />
          <p className="text-limit">{translations.homePage.description[language]}</p>
      </Container>
    </>
  );
}
