import { Container } from "react-bootstrap"
import Head from 'next/head'

export default function Home() {
  return (
    <>
    <Head>
        <title>Harry Potter Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
        <Container>
            <h1 className="text-center">Welcome to PotterWeb</h1>
            <p className="text-center">Choose a language to get started</p>
        </Container>
    </>
  );
}
