import { Container } from "react-bootstrap"
import Head from 'next/head'
import { translations } from "@/lib/lang";
import { useContext } from "react";
import LanguageContext from "@/lib/languageContext";

export default function Home() {
  const { language } = useContext(LanguageContext);
  return (
    <>
    <Head>
        <title>Harry Potter Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
        <Container>
            <h1 className="text-center">{translations.homePage.title[language]}</h1>
            <p className="text-center">{translations.homePage.description[language]}</p>
        </Container>
    </>
  );
}
